# Generated by Django 5.2.14 on 2026-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyhooker', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skyhooksnapshot',
            new_name='skyhooker_s_skyhook_137bd7_idx',
            old_name='skyhooker_snap_idx',
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skyhook',
            name='current_state',
            field=models.CharField(choices=[('Anchoring', 'Anchoring'), ('Unanchoring', 'Unanchoring'), ('ShieldVulnerable', 'Shield Vulnerable'), ('PartiallyShieldVulnerable', 'Partially Shield Vulnerable'), ('ShieldReinforced', 'Shield Reinforced'), ('ArmorReinforced', 'Armor Reinforced'), ('HullReinforced', 'Hull Reinforced'), ('HullVulnerable', 'Hull Vulnerable'), ('Online', 'Online'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='skyhook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skyhookcorporation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skyhooksnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skyhooksnapshot',
            name='secured_delta',
            field=models.BigIntegerField(blank=True, help_text='Change in secured stock vs previous snapshot (negative = retrieved)', null=True),
        ),
        migrations.AlterField(
            model_name='skyhooksnapshot',
            name='unsecured_delta',
            field=models.BigIntegerField(blank=True, help_text='Change in unsecured stock vs previous snapshot (negative = possible theft)', null=True),
        ),
    ]
