# Generated by Django 5.2.14 on 2026-06-06 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyhooker', '0002_rename_skyhooker_snap_idx_skyhooker_s_skyhook_137bd7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='amount_delta',
            field=models.BigIntegerField(blank=True, help_text='Units dropped at time of alert', null=True),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='discord_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AlertResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('theft', 'Confirmed Theft'), ('recovered', 'Recovered'), ('false_alarm', 'False Alarm')], max_length=20)),
                ('amount', models.BigIntegerField(help_text='Units lost or recovered (from the alert delta)')),
                ('resolved_by_discord_id', models.CharField(blank=True, max_length=64)),
                ('resolved_by_name', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='skyhooker.alertlog')),
            ],
            options={
                'verbose_name': 'Alert Resolution',
                'verbose_name_plural': 'Alert Resolutions',
                'ordering': ['-resolved_at'],
            },
        ),
    ]
